name: Release to Maven Central

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: central
          server-username: OSS_NEXUS_USER
          server-password: OSS_NEXUS_PASS
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build and Deploy to Maven Central
        run: mvn -B clean deploy -P release
        env:
          OSS_NEXUS_USER: ${{ secrets.OSS_NEXUS_USER }}
          OSS_NEXUS_PASS: ${{ secrets.OSS_NEXUS_PASS }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}